 # Below are all the sections and options you can have in  ~/.streamlit/config.toml.


[global]

# By default, Streamlit checks if the Python watchdog module is available
# and, if not, prints a warning asking for you to install it. The watchdog
# module is not required, but highly recommended. It improves Streamlit's
# ability to detect changes to files in your filesystem.

# If you'd like to turn off this warning, set this to True.


disableWatchdogWarning = false

# By default, Streamlit displays a warning when a user sets both a widget
# default value in the function defining the widget and a widget value via
# the widget's key in `st.session_state`.

# If you'd like to turn off this warning, set this to True.


disableWidgetStateDuplicationWarning = false

# If True, will show a warning when you run a Streamlit-enabled script
# via "python my_script.py".


showWarningOnDirectExecution = true

# DataFrame serialization.

# Acceptable values:
# - 'legacy': Serialize DataFrames using Streamlit's custom format. Slow
# but battle-tested.
# - 'arrow': Serialize DataFrames using Apache Arrow. Much faster and versatile.


dataFrameSerialization = "arrow"


[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.


level = "info"

# String format for logging messages. If logger.datetimeFormat is set,
# logger messages will default to `%(asctime)s.%(msecs)03d %(message)s`. See
# [Python's documentation](https://docs.python.org/2.6/library/logging.html#formatter-objects)
# for available attributes.


[client]

# Whether to enable st.cache. This does not affect st.cache_data or
# st.cache_resource.


caching = true

showErrorDetails = true

toolbarMode = "auto"


[runner]

# Allows you to type a variable or string by itself in a single line of
# Python code to write it to the app.


magicEnabled = true

# Install a Python tracer to allow you to stop or pause your script at
# any point and introspect it. As a side-effect, this slows down your
# script's execution.


installTracer = false

fastReruns = true

enforceSerializableSessionState = false


[server]

fileWatcherType = "auto"

# The port where the server will listen for browser connections.

port = 8501

[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = dark